title: Phoebe Choi, ACAS
#logo: 
description: Actuary with background in Data Science and Finance
#show_downloads: true
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag # Add SEO plugin

social_links:
linkedin: phoebecmk
email: phoebe.choi.mk@gmail.com
